services:
  - type: web
    name: javoucar-socket-server
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000