services:
  - type: web
    name: javoucar-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true